import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="container m-5">
        <div class="grid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Yeni Kayıt</h5>
                        </div>
                        <div class="card-body">
                            <div class="grid">
                                <div class="row">
                                    <div class="col-12 col-md-4">
                                        <label class="form-label">Adı</label>
                                        <input id="txtFirstName" class="form-control" autocomplete="off" />
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <label class="form-label">Soyadı</label>
                                        <input id="txtLastName" class="form-control" autocomplete="off" />
                                    </div>
                                    <div class="col-12 col-md-4">
                                        <label class="form-label">Adı</label>
                                        <input id="txtBirthDate" class="form-control" type="date" autocomplete="off" />
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-12 d-flex justify-content-end">
                                        <button class="btn btn-primary" va-click="save">Kaydet</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-12 col-md-6">
                    <ul class="list-group list-group-flush" va-array="participants">
                        
                    </ul>
                </div>
                <div class="col-12 col-md-6">
                    <ul class="list-group list-group-flush" va-array="selected">
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </>
  );
}
